export const userAdminAccessOptions = [
  { role: "Vehicle Master", permissionBit: 1 },
  { role: "Asset Verification", permissionBit: 1 },
  { role: "Accidents", permissionBit: 1 },
  { role: "Call Centre", permissionBit: 1 },
  { role: "Fines", permissionBit: 1 },
  { role: "Licence", permissionBit: 1 },
  { role: "Losses", permissionBit: 1 },
  { role: "Tracking", permissionBit: 1 },
  { role: "Towing", permissionBit: 1 },
  { role: "Trip Authorities", permissionBit: 1 },
  { role: "Private Hire Vehicles", permissionBit: 1 },
  { role: "Taxis", permissionBit: 1 },
  { role: "Clearance", permissionBit: 1 },
  { role: "Contracts", permissionBit: 2 },
  { role: "User Administration", permissionBit: 4 },
  { role: "Reports", permissionBit: 8 },
  { role: "Management Reports", permissionBit: 8 },
  { role: "Logbooks", permissionBit: 8 },
  { role: "Logsheets", permissionBit: 8 },
  { role: "Monitor", permissionBit: 8 },
  { role: "Fuelcards", permissionBit: 16 },
  { role: "Auction", permissionBit: 16 },
  { role: "Financial Data (All Departments)", permissionBit: 16 },
  { role: "Financial Data (Own Department)", permissionBit: 16 },
  { role: "Financial Reports", permissionBit: 16 },
  { role: "Workshop", permissionBit: 32 },
  { role: "Trouble Shooting", permissionBit: 32 },
] as const;
