import type { DepartmentRecord } from "@/lib/api-departments";

export const emptyDepartment: DepartmentRecord = {
  departmentCode: 0,
  companyCode: 1,
  description: null,
  responsiblePerson: null,
  address1: null,
  address2: null,
  address3: null,
  postalCode: null,
  telephone: null,
  fax: null,
  netAddress: null,
  departmentNumber: null,
  cellNumber: null,
  notes: null,
  departmentAbbr: null,
  basInstallationCode: null,
  deptActive: true,
  cloEmail: null,
  telephone2: null,
  fax2: null,
  financialSystemCode: null,
  financialSystemActive: null,
  financialSystemActivateDate: null,
  defaultSite: null,
  exportIsActive: null,
  dateLastExported: null,
  serviceKilometres: 0,
  serviceYears: 0,
  overheadPercentage: 0,
  dateCreated: null,
  dateUpdated: null,
  userAccessCode: null,
  modifiedByUserCode: null,
  comments: null,
};
