namespace FIS.Web.Components.Pages.Users;

public static class UserAdminRoleData
{
    public sealed record RoleAccessOption(string Role, long? PermissionBit);

    public static readonly string[] Roles =
    [
        "Accidents",
        "Acquisition",
        "Asset Verification",
        "Auction",
        "BAS Journal Parameters",
        "Back Dating Contract (Approver)",
        "Call Centre",
        "Clearance",
        "Contracts",
        "Contract (Load and Manage)",
        "Contract (Cancel and Close)",
        "Contract (Approver)",
        "Demo Vehicles",
        "Departmental Contracts",
        "Financial Data (All Departments)",
        "Financial Data (Own Department)",
        "Financial Reports",
        "Financial Tariff Parameters",
        "Financial Tariff Parameters (Approver)",
        "Advanced Financial Operations - Batch",
        "Fines",
        "Fuelcards",
        "GG Number Maintenance",
        "GGMT BAS Transfer Parameters",
        "Help Desk Functions",
        "JobCard Authorizer",
        "JobCard Capturer",
        "Lease Vehicle Authorizer",
        "Lease Vehicle Capturer",
        "Lease Vehicle Pending",
        "Licence",
        "Logbooks",
        "Logistics",
        "Logsheets",
        "Losses",
        "Losses HQ",
        "Management Reports",
        "Missing Vehicles",
        "Monitor",
        "Private Hire Vehicles",
        "Reports",
        "SystemAdministrator",
        "Taxi information maintenance",
        "Taxi Invoices",
        "Towing",
        "Tracking",
        "Trip Authorities",
        "Trouble Shooting",
        "User Administration",
        "Validation",
        "Vehicle Inception Authorizer",
        "Vehicle Inception Capturer",
        "Vehicle List for All Departments in Province",
        "Vehicle List for All Sites in Department",
        "Vehicle Master",
        "TSS",
        "Workshop",
        "Book Recurring Taxi",
        "Contract History Back Dating",
        "Driver and Authoriser Management"
    ];

    public static readonly RoleAccessOption[] AccessOptions =
    [
        new("Vehicle Master", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Asset Verification", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Accidents", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Call Centre", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Fines", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Licence", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Losses", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Tracking", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Towing", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Trip Authorities", FIS.Web.Services.LegacyPermissionBits.VehicleManagement),
        new("Contracts", FIS.Web.Services.LegacyPermissionBits.ContractManagement),
        new("Contract (Load and Manage)", FIS.Web.Services.LegacyPermissionBits.ContractManagement),
        new("Contract (Cancel and Close)", FIS.Web.Services.LegacyPermissionBits.ContractManagement),
        new("Contract (Approver)", FIS.Web.Services.LegacyPermissionBits.ContractManagement),
        new("Back Dating Contract (Approver)", FIS.Web.Services.LegacyPermissionBits.ContractManagement),
        new("User Administration", FIS.Web.Services.LegacyPermissionBits.UserAdministration),
        new("Reports", FIS.Web.Services.LegacyPermissionBits.Reports),
        new("Management Reports", FIS.Web.Services.LegacyPermissionBits.Reports),
        new("Financial Data (All Departments)", FIS.Web.Services.LegacyPermissionBits.Financial),
        new("Financial Data (Own Department)", FIS.Web.Services.LegacyPermissionBits.Financial),
        new("Financial Reports", FIS.Web.Services.LegacyPermissionBits.Financial),
        new("Workshop", FIS.Web.Services.LegacyPermissionBits.Workshop)
    ];
}
